### ISSUE TITLE
Missing dependencies after successful installation

### ISSUE THREAD

**Issue by AnzhelikaVetMedUni** [MayurDivate/GUAVASourceCode#3]
Hey!

I have been trying to get GUAVA working for ATAC-seq analysis. I have installed GUAVA according to the manual and everything seems to have gone successfully:

I_NSTALLING GUAVA-1 dependencies
>>>>>> Operating system :Mac
>>> R is already installed !
>>> R is already installed !
>>> >> > Installing R packages > >> >
[1] ">>> >> > Loading BIOCONDUCTOR > >> >>>"
Bioconductor version 3.7 (BiocInstaller 1.30.0), ?biocLite for help
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.7 (BiocInstaller 1.30.0), R 3.5.1 (2018-07-02).
[1] ">>> >> > checking required packages > >> >>>"
[1] ">>>>> Found: ggplot2 <<<<<"
[1] ">>>>> Found:  GenomicFeatures <<<<<"
[1] ">>>>> Found:  TxDb.Hsapiens.UCSC.hg19.knownGene <<<<<"
[1] ">>>>> Found:  TxDb.Mmusculus.UCSC.mm10.knownGene <<<<<"
[1] ">>>>> Found:  org.Hs.eg.db <<<<<"
[1] ">>>>> Found:  org.Mm.eg.db <<<<<"
[1] ">>>>> Found:  ChIPpeakAnno <<<<<"
[1] ">>>>> Found:  GO.db <<<<<"
[1] ">>>>> Found:  KEGG.db <<<<<"
[1] ">>>>> Found:  Rsubread <<<<<"
[1] ">>>>> Found:  DESeq2 <<<<<"

>>> CONDA is already installed !

---------- Adding BIOCONDA and other channels ----------------
Warning: 'r' already in 'channels' list, moving to the top
Warning: 'defaults' already in 'channels' list, moving to the top
Warning: 'conda-forge' already in 'channels' list, moving to the top
Warning: 'bioconda' already in 'channels' list, moving to the top

>>> >> > Installing dependencies > >> >>>
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
>>>>> FOUND: java <<<<<
>>>>> FOUND: bedtools <<<<<
>>>>> FOUND: bowtie <<<<<
>>>>> FOUND: bowtie2 <<<<<
>>>>> FOUND: cutadapt <<<<<
>>>>> FOUND: fastqc <<<<<
>>>>> FOUND: samtools <<<<<
>>>>> FOUND: picard <<<<<
>>>>> FOUND: igv <<<<<
>>>>> FOUND: bedGraphToBigWig <<<<<

>>> MACS2 is already installed ! 
>>>>>>>>> Finished <<<<<<<<<_

But when I try to run the ATAC-seq data analysis MACS2 seems to be missing:

G_UAVA version 1_
_Operating System of machine :Mac OS X
		cutadapt:		Working!
		bowtie:		Working!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		**MACS2 version (macs2 2.1.1.20160309) :			NOT FOUND !!!**
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!

**There are missing dependancies!**
Please use configure.sh to install dependencies.
If you are having difficulties in installing dependencies, please report issue at *GitHub*.
>>> https://github.com/MayurDivate/GUAVASourceCode/issues
EXIT(GUAVA) ..._ 

So I am not quite sure what to do. Could you possibly help?

Thank you!

Anzhelika

**Comment by syed1789** [comment]
I also having the same problem..

**Comment by MayurDivate** [comment]
Hello everyone, 

Sorry for the late reply. 

Recently MACS2 got updated from 2.1.1.20160309 to 2.1.1 version.
As GUAVA automatically installs the latest MACS2 version you get the above error.

Please use the command below to install correct MACS2 version. 
pip install MACS2==2.1.1.20160309 
(use sudo if required)

We will fix this issue in the upcoming release. 

Cheers,
Mayur

**Comment by syed1789** [comment]
thanks

**Comment by jrainger3** [comment]
I am having the same problem, but when I run..
pip install MACS2==2.1.1.20160309
it says
Complete output from command python setup.py egg_info:
CRITICAL:Numpy must be installed!    
 ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vv/yh9n7lws3gs_xn322srw52dnggt16m/T/pip-install-jvDqP5/MACS2/

Please help. Thanks!

**Comment by jrainger3** [comment]
I fixed it using this:
$ python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
$ pip install MACS2==2.1.1.20160309
$ sh ./configure.sh
All good!

**Comment by woeulii** [comment]
Hi,
I am new to GUAVA and also get the problem with MACS2. I tried all of the suggestions above but still get this error:

(base) tsf-484-wpa-5-096:~ wohlwend$ pip install MACS2==2.1.1.20160309
Collecting MACS2==2.1.1.20160309
  Using cached https://files.pythonhosted.org/packages/9f/99/a8ac96b357f6b0a6f559fe0f5a81bcae12b98579551620ce07c5183aee2c/MACS2-2.1.1.20160309.tar.gz
Requirement already satisfied: numpy>=1.6 in ./miniconda2/lib/python2.7/site-packages (from MACS2==2.1.1.20160309) (1.16.2)
Building wheels for collected packages: MACS2
  Running setup.py bdist_wheel for MACS2 ... error
  Complete output from command /Users/wohlwend/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/v2/08jgbwrd35d3qvt23279xrmw0000gn/T/pip-install-3MxBPE/MACS2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/v2/08jgbwrd35d3qvt23279xrmw0000gn/T/pip-wheel-6Hpc6q --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/OutputWriter.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/refinepeak_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/cmbreps_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/pileup_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/bdgcmp_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/Constants.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/bdgdiff_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/predictd_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/filterdup_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/bdgopt_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/OptValidator.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/callpeak_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/bdgbroadcall_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/bdgpeakcall_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/randsample_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  copying MACS2/diffpeak_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
  creating build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
  copying MACS2/IO/test_processing.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
  copying MACS2/IO/test_threading.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
  copying MACS2/IO/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
  copying MACS2/IO/BinKeeper.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
  running build_ext
  building 'MACS2.Prob' extension
  creating build/temp.macosx-10.6-x86_64-2.7
  creating build/temp.macosx-10.6-x86_64-2.7/MACS2
  gcc -fno-strict-aliasing -I/Users/wohlwend/miniconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/wohlwend/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/wohlwend/miniconda2/include/python2.7 -c MACS2/Prob.c -o build/temp.macosx-10.6-x86_64-2.7/MACS2/Prob.o -w -O3 -ffast-math
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for MACS2
  Running setup.py clean for MACS2
Failed to build MACS2
Installing collected packages: MACS2
  Running setup.py install for MACS2 ... error
    Complete output from command /Users/wohlwend/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/v2/08jgbwrd35d3qvt23279xrmw0000gn/T/pip-install-3MxBPE/MACS2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/v2/08jgbwrd35d3qvt23279xrmw0000gn/T/pip-record-Z50iQb/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-2.7
    creating build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/OutputWriter.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/refinepeak_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/cmbreps_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/pileup_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/bdgcmp_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/Constants.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/bdgdiff_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/predictd_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/filterdup_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/bdgopt_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/OptValidator.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/callpeak_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/bdgbroadcall_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/bdgpeakcall_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/randsample_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    copying MACS2/diffpeak_cmd.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2
    creating build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
    copying MACS2/IO/test_processing.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
    copying MACS2/IO/test_threading.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
    copying MACS2/IO/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
    copying MACS2/IO/BinKeeper.py -> build/lib.macosx-10.6-x86_64-2.7/MACS2/IO
    running build_ext
    building 'MACS2.Prob' extension
    creating build/temp.macosx-10.6-x86_64-2.7
    creating build/temp.macosx-10.6-x86_64-2.7/MACS2
    gcc -fno-strict-aliasing -I/Users/wohlwend/miniconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/wohlwend/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/wohlwend/miniconda2/include/python2.7 -c MACS2/Prob.c -o build/temp.macosx-10.6-x86_64-2.7/MACS2/Prob.o -w -O3 -ffast-math
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/wohlwend/miniconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/v2/08jgbwrd35d3qvt23279xrmw0000gn/T/pip-install-3MxBPE/MACS2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/v2/08jgbwrd35d3qvt23279xrmw0000gn/T/pip-record-Z50iQb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/v2/08jgbwrd35d3qvt23279xrmw0000gn/T/pip-install-3MxBPE/MACS2/

Any help is greatly appreciated!
Thanks in advance!

**Comment by roshsin** [comment]
Hello again,

I resolved miniconda loading issue. But, I am now running into MAC2S installation errors even though I have tried using different versions of Python (2.7, 3.6, 3.7). 
Additionally, I am observing dyld: Library not loaded.
I tried all the suggestions mentioned here but it didn't work. 
Kindly advise on how I can overcome these!

Attached below are the errors I am running into right now:

INSTALLING GUAVA-1 dependencies
>>>>>> Operating system :Mac
>>> R is already installed !
>>> R is already installed !
>>> >> > Installing R packages > >> >
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/roshanisinha/miniconda3/envs/mywork2/lib/R/lib/libR.dylib
  Reason: image not found
./configure.sh: line 96: 26743 Abort trap: 6           Rscript ./lib/InstallRequiredPackages.R

>>> CONDA is already installed !

---------- Adding BIOCONDA and other channels ----------------
Warning: 'r' already in 'channels' list, moving to the top
Warning: 'defaults' already in 'channels' list, moving to the top
Warning: 'conda-forge' already in 'channels' list, moving to the top
Warning: 'bioconda' already in 'channels' list, moving to the top


>>> >> > Installing dependencies > >> >>>
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
>>>>> FOUND: java <<<<<
>>>>> FOUND: bedtools <<<<<
>>>>> FOUND: bowtie <<<<<
>>>>> FOUND: bowtie2 <<<<<
>>>>> FOUND: cutadapt <<<<<
>>>>> FOUND: fastqc <<<<<
>>>>> FOUND: samtools <<<<<
>>>>> FOUND: picard <<<<<
>>>>> FOUND: igv <<<<<
>>>>> FOUND: bedGraphToBigWig <<<<<

>>> >> > Installing Numpy > >> >>>
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: numpy in /Users/roshanisinha/miniconda3/envs/mywork2/lib/python2.7/site-packages (1.16.6)

>>> >> > Installing MACS2 > >> >>>
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting macs2
  Using cached MACS2-2.2.6.tar.gz (2.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/roshanisinha/miniconda3/envs/mywork2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-esZVEH/macs2/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-esZVEH/macs2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-B143Qx
         cwd: /private/tmp/pip-install-esZVEH/macs2/
    Complete output (1 lines):
    CRITICAL: Python version must >= 3.6!
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
>>>>>>>>> Finished <<<<<<<<<

Thank you!

Rosh
